networks:
  rtcw:
    name: rtcw
    external: true

x-common-core: &common-core
  image: msh100/rtcw
  env_file: stack.env
  networks:
    - rtcw
  environment:
    - 'HOSTNAME=EU RtCW CUP/Gather Server'
  labels:
    - "com.centurylinklabs.watchtower.enable=true"
    - "com.centurylinklabs.watchtower.lifecycle.pre-update=/home/game/autorestart"
  stdin_open: true
  tty: true
  restart: unless-stopped

services:
  rtcw1:
    <<: *common-core
    container_name: rtcw1
    volumes:
      - "$MAPDIR:/maps/"
      - "$LOGDIR/rtcw1:/home/game/rtcwpro/logs"
      - "$STATS/rtcw1:/home/game/rtcwpro/stats"
    ports:
      - '27960:27960/udp'

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    command: --http-api-update --enable-lifecycle-hooks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/config.json
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=$WATCHTOWER_API_TOKEN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080